#!/bin/bash
# Build script for Render
# Captures git SHA and writes to .build-info.py

set -e

# Capture git info
GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

# Write to build info file
cat > .build-info.py <<EOF
"""
Build-time script to capture git SHA.
This file is generated during build and read at runtime.
"""
# This file is auto-generated by build script
GIT_SHA = "$GIT_SHA"
GIT_BRANCH = "$GIT_BRANCH"
EOF

echo "Build info: SHA=$GIT_SHA, Branch=$GIT_BRANCH"

# Install dependencies
pip install -r requirements.txt

